Repository redisson/redisson, pull requests merged in 2020-12, with the labels that each got.

#3235 RedisNodes ping results check optimization
  redisson/src/main/java/org/redisson/RedisNodes.java
Labels: enhancement

#3269 fix: ConnectionWatchdog connection leak;
  redisson/src/main/java/org/redisson/client/handler/ConnectionWatchdog.java
Labels: bug

#3219 Enhance PropertiesDecoder decoding performance
  redisson-spring-data/redisson-spring-data-16/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java
  redisson-spring-data/redisson-spring-data-17/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java
  redisson-spring-data/redisson-spring-data-18/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java
  redisson-spring-data/redisson-spring-data-20/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java
  redisson-spring-data/redisson-spring-data-21/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java
  redisson-spring-data/redisson-spring-data-22/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java
  redisson-spring-data/redisson-spring-data-23/src/main/java/org/redisson/spring/data/connection/PropertiesDecoder.java
  redisson-spring-data/redisson-spring-data-23/src/test/java/org/redisson/spring/data/connection/PropertiesDecoderTest.java
Labels: enhancement

#3292 Fix check parameter code error and optimize code format
  redisson/src/main/java/org/redisson/RedissonMap.java
Labels: bug

#3295 fix: connection leak when initConnections
  redisson/src/main/java/org/redisson/connection/ClientConnectionsEntry.java
  redisson/src/main/java/org/redisson/connection/balancer/LoadBalancerManager.java
Labels: bug

#3293 Feature - Added option to allow null values in a local cache #3221
  redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java
  redisson/src/main/java/org/redisson/api/LocalCachedMapOptions.java
  redisson/src/test/java/org/redisson/RedissonLocalCachedMapTest.java
Labels: feature
