Repository redisson/redisson, pull requests merged in 2021-01, with the labels that each got.

#3339 Add RedisBusyException. In case of the watchdog logic exit during red…
  redisson/src/main/java/org/redisson/client/RedisBusyException.java
  redisson/src/main/java/org/redisson/client/handler/CommandDecoder.java
  redisson/src/main/java/org/redisson/command/RedisExecutor.java
Labels: enhancement

#3355 Set connection to fail when all slaves init connections error
  redisson/src/main/java/org/redisson/cluster/ClusterConnectionManager.java
Labels: bug

#3364 Implemented spin locks
  redisson/src/main/java/org/redisson/Redisson.java
  redisson/src/main/java/org/redisson/RedissonBaseLock.java
  redisson/src/main/java/org/redisson/RedissonLock.java
  redisson/src/main/java/org/redisson/RedissonReactive.java
  redisson/src/main/java/org/redisson/RedissonRx.java
  redisson/src/main/java/org/redisson/RedissonSpinLock.java
  redisson/src/main/java/org/redisson/api/LockOptions.java
  redisson/src/main/java/org/redisson/api/RedissonClient.java
  redisson/src/main/java/org/redisson/api/RedissonReactiveClient.java
  redisson/src/main/java/org/redisson/api/RedissonRxClient.java
  redisson/src/test/java/org/redisson/LockOptionsTest.java
  redisson/src/test/java/org/redisson/RedissonSpinLockTest.java
Labels: feature
