Repository redisson/redisson, pull requests merged in 2023-08, with the labels that each got.

#5170 Feature - Netty native transport for `io_uring`
  redisson/pom.xml
  redisson/src/main/java/org/redisson/config/TransportMode.java
  redisson/src/main/java/org/redisson/connection/ServiceManager.java
Labels: feature

#5243 Cache Long as strings in CommandEncoder in order to reduce allocations and improve performance
  redisson/src/main/java/org/redisson/client/handler/CommandEncoder.java
Labels: enhancement

#5262 Protobuf support
  redisson/pom.xml
  redisson/src/main/java/org/redisson/codec/ProtobufCodec.java
  redisson/src/test/java/org/redisson/RedissonCodecTest.java
  redisson/src/test/java/org/redisson/codec/protobuf/ProtobufCodecTest.java
  redisson/src/test/java/org/redisson/codec/protobuf/nativeData/Proto2AllTypes.java
  redisson/src/test/java/org/redisson/codec/protobuf/nativeData/Proto3AllTypes.java
  redisson/src/test/java/org/redisson/codec/protobuf/nativeData/proto2AllTypes.proto
  redisson/src/test/java/org/redisson/codec/protobuf/nativeData/proto3AllTypes.proto
  redisson/src/test/java/org/redisson/codec/protobuf/protostuffData/StuffData.java
Labels: feature

#4979 fix: semaphore pub when permits not updated
  redisson/src/main/java/org/redisson/RedissonPermitExpirableSemaphore.java
Labels: bug

#5247 Feature: multiple permit RedissonPermitExpirableSemaphore
  redisson/src/main/java/org/redisson/RedissonPermitExpirableSemaphore.java
  redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphore.java
  redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphoreAsync.java
  redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphoreReactive.java
  redisson/src/main/java/org/redisson/api/RPermitExpirableSemaphoreRx.java
  redisson/src/main/java/org/redisson/client/protocol/RedisCommands.java
  redisson/src/main/java/org/redisson/client/protocol/decoder/PermitDecoder.java
  redisson/src/test/java/org/redisson/RedissonPermitExpirableSemaphoreTest.java
Labels: feature
