Repository redisson/redisson, pull requests merged in 2023-10, with the labels that each got.

#5294 Support retry for WRITE_THROUGH and WRITE_BEHIND
  redisson/src/main/java/org/redisson/RedissonMap.java
  redisson/src/main/java/org/redisson/api/MapOptions.java
  redisson/src/main/java/org/redisson/api/map/RetryableMapWriter.java
  redisson/src/main/java/org/redisson/api/map/RetryableMapWriterAsync.java
  redisson/src/test/java/org/redisson/BaseMapTest.java
Labels: feature

#5350 Fix RCountDownLatch only notifying the first async listener after countdown reaches 0
  redisson/src/main/java/org/redisson/pubsub/CountDownLatchPubSub.java
  redisson/src/test/java/org/redisson/pubsub/CountDownLatchPubSubTest.java
Labels: bug

#5315 Fixes waitTime loses unit when passed to tryLockInnerAsync
  redisson/src/main/java/org/redisson/RedissonLock.java
Labels: bug

#5361 Missing methods in Quarkus Native
  redisson-quarkus/redisson-quarkus-30/deployment/src/main/java/io/quarkus/redisson/client/deployment/QuarkusRedissonClientProcessor.java
  redisson-quarkus/redisson-quarkus-30/integration-tests/src/main/java/org/redisson/quarkus/client/it/QuarkusRedissonClientResource.java
  redisson-quarkus/redisson-quarkus-30/integration-tests/src/test/java/org/redisson/quarkus/client/it/QuarkusRedissonClientResourceTest.java
Labels: bug

#5370 ConnectionManger.shutdown completes within timeout
  redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java
Labels: enhancement
