Repository redisson/redisson, pull requests merged in 2024-11, with the labels that each got.

#6266 Fix potential memory leak on method LocalCacheView.toCacheKey if useObjectAsCacheKey = true
  redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java
  redisson/src/main/java/org/redisson/cache/LocalCacheView.java
Labels: bug

#5147 Code Review - Behaviors of FixedRate and FixedDelay should be similar in TasksRunnerService
  redisson/src/main/java/org/redisson/executor/TasksRunnerService.java
  redisson/src/test/java/org/redisson/executor/RedissonScheduledExecutorServiceTest.java
  redisson/src/test/java/org/redisson/executor/SwallowingInterruptionTask.java
Labels: bug

#6274 use CursorId in ScanIteration to avoid long overflow
  redisson-spring-data/redisson-spring-data-33/src/main/java/org/redisson/spring/data/connection/RedissonClusterConnection.java
  redisson-spring-data/redisson-spring-data-33/src/main/java/org/redisson/spring/data/connection/RedissonConnection.java
Labels: improvement

#6290 Fixed - TypedJsonJacksonCodec should catch Exception #6286
  redisson/src/main/java/org/redisson/codec/TypedJsonJacksonCodec.java
Labels: bug

#6295 Fixed - method lengthAsync of RedissonBitSet
  redisson/src/main/java/org/redisson/RedissonBitSet.java
  redisson/src/test/java/org/redisson/RedissonBitSetTest.java
Labels: bug

#6299 Feature - Atomic class add greaterThanSet and lessThanSet method
  redisson/src/main/java/org/redisson/RedissonAtomicDouble.java
  redisson/src/main/java/org/redisson/RedissonAtomicLong.java
  redisson/src/main/java/org/redisson/api/RAtomicDouble.java
  redisson/src/main/java/org/redisson/api/RAtomicDoubleAsync.java
  redisson/src/main/java/org/redisson/api/RAtomicDoubleReactive.java
  redisson/src/main/java/org/redisson/api/RAtomicDoubleRx.java
  redisson/src/main/java/org/redisson/api/RAtomicLong.java
  redisson/src/main/java/org/redisson/api/RAtomicLongAsync.java
  redisson/src/main/java/org/redisson/api/RAtomicLongReactive.java
  redisson/src/main/java/org/redisson/api/RAtomicLongRx.java
  redisson/src/test/java/org/redisson/RedissonAtomicDoubleTest.java
  redisson/src/test/java/org/redisson/RedissonAtomicLongReactiveTest.java
  redisson/src/test/java/org/redisson/RedissonAtomicLongTest.java
Labels: feature

#6300 Add fastReplaceValuesAsync and fastReplaceValues to RMultimap and its implementations.
  redisson/src/main/java/org/redisson/RedissonListMultimap.java
  redisson/src/main/java/org/redisson/RedissonSetMultimap.java
  redisson/src/main/java/org/redisson/api/RMultimap.java
  redisson/src/main/java/org/redisson/api/RMultimapAsync.java
  redisson/src/main/java/org/redisson/api/RMultimapReactive.java
  redisson/src/main/java/org/redisson/api/RMultimapRx.java
  redisson/src/test/java/org/redisson/RedissonListMultimapTest.java
  redisson/src/test/java/org/redisson/RedissonSetMultimapTest.java
Labels: feature
