Repository redisson/redisson, pull requests merged in 2024-08, with the labels that each got.

#6080 Fix RMapCacheNative expiring keyspace event using the wrong key
  redisson/src/main/java/org/redisson/RedissonMapCacheNative.java
Labels: bug

#6084 Fixed - caused RedisException when execute lua-script
  redisson/src/main/java/org/redisson/RedissonSubList.java
  redisson/src/test/java/org/redisson/RedissonListTest.java
Labels: bug

#3118 Fix in RedissonExecutorService
  redisson/src/main/java/org/redisson/RedissonExecutorService.java
Labels: bug

#6089 Optimization: Don't take lock in computeIfAbsent if only get is needed
  redisson/src/main/java/org/redisson/RedissonMap.java
Labels: improvement

#6090 Redisearch FT.INFO result decoder throws NumberFormatException
  redisson/src/main/java/org/redisson/api/search/index/IndexInfo.java
  redisson/src/main/java/org/redisson/client/protocol/decoder/IndexInfoDecoder.java
Labels: bug

#6094 Improvement - Copy command execute through multi db
  redisson/src/main/java/org/redisson/RedissonObject.java
  redisson/src/test/java/org/redisson/RedisDockerTest.java
  redisson/src/test/java/org/redisson/RedissonBucketTest.java
  redisson/src/test/java/org/redisson/RedissonIdGeneratorTest.java
Labels: bug

#6077 wrap ByteBuf into Fury Buffer for zero-copy deserialization
  redisson/src/main/java/org/redisson/codec/FuryCodec.java
Labels: improvement

#6120 Allow to specify WITHCOUNT in QueryOptions / AggregationOptions
  redisson/src/main/java/org/redisson/RedissonSearch.java
  redisson/src/main/java/org/redisson/api/search/aggregate/AggregationOptions.java
  redisson/src/main/java/org/redisson/api/search/query/QueryOptions.java
Labels: feature
