Repository redisson/redisson, pull requests merged in 2024-06, with the labels that each got.

#5929 Fixed - Concurrency problem
  redisson/src/main/java/org/redisson/RedissonBaseLock.java
Labels: bug

#5949 Feature - RedissonKeys implements UnlinkByPattern and unlinkByPatternAsync methods
  redisson/src/main/java/org/redisson/RedissonKeys.java
  redisson/src/main/java/org/redisson/api/RKeys.java
  redisson/src/main/java/org/redisson/api/RKeysAsync.java
  redisson/src/main/java/org/redisson/api/RKeysReactive.java
  redisson/src/main/java/org/redisson/api/RKeysRx.java
  redisson/src/test/java/org/redisson/RedissonKeysReactiveTest.java
  redisson/src/test/java/org/redisson/RedissonKeysTest.java
  redisson/src/test/java/org/redisson/rx/RedissonKeysRxTest.java
Labels: feature

#5957 Fixed - Redisearch get index info throws NumberFormatException #5950
  redisson/src/main/java/org/redisson/api/search/index/IndexInfo.java
  redisson/src/main/java/org/redisson/client/protocol/decoder/IndexInfoDecoder.java
Labels: bug

#5958 Fixed - Redisearch parse params error
  redisson/src/main/java/org/redisson/RedissonSearch.java
  redisson/src/test/java/org/redisson/RedissonSearchTest.java
Labels: bug

#5915 Fix #5426
  redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSession.java
  redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
  redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSession.java
  redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
  redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java
  redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
  redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSession.java
  redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java
Labels: bug, tomcat

#5991 Fixed - RingBuffer#setCapacity, trim list incorrect
  redisson/src/main/java/org/redisson/RedissonRingBuffer.java
  redisson/src/test/java/org/redisson/RedissonRingBufferTest.java
Labels: bug
