Repository redisson/redisson, pull requests merged in 2024-10, with the labels that each got.

#6196 Support to cache method LocalCacheView.toCacheKey(Object) for CacheProvider.REDISSON
  redisson/src/main/java/org/redisson/RedissonLocalCachedMap.java
  redisson/src/main/java/org/redisson/api/LocalCachedMapOptions.java
  redisson/src/main/java/org/redisson/cache/AbstractCacheMap.java
  redisson/src/main/java/org/redisson/cache/LocalCacheListener.java
  redisson/src/main/java/org/redisson/cache/LocalCacheView.java
Labels: feature

#6212 Redisearch FT.INFO result decoder throws on infinity values
  redisson/src/main/java/org/redisson/client/protocol/decoder/IndexInfoDecoder.java
Labels: bug

#6220 Add check code for RRateLimiter.trySetRate
  redisson/src/main/java/org/redisson/RedissonRateLimiter.java
Labels: bug

#6222 Improvement - Change timeToLive to keepAliveTime #6216
  redisson/src/main/java/org/redisson/RedissonRateLimiter.java
  redisson/src/main/java/org/redisson/api/RRateLimiter.java
  redisson/src/test/java/org/redisson/RedissonRateLimiterTest.java
Labels: improvement

#6206 Feature - Add RedissonFasterMultiLock
  redisson/src/main/java/org/redisson/Redisson.java
  redisson/src/main/java/org/redisson/RedissonFasterMultiLock.java
  redisson/src/main/java/org/redisson/RedissonReactive.java
  redisson/src/main/java/org/redisson/RedissonRx.java
  redisson/src/main/java/org/redisson/api/RedissonClient.java
  redisson/src/main/java/org/redisson/api/RedissonReactiveClient.java
  redisson/src/main/java/org/redisson/api/RedissonRxClient.java
  redisson/src/test/java/org/redisson/RedissonFasterMultiLockTest.java
Labels: feature

#6227 Make search available via batch (pipelining). Fixes #6125.
  redisson/src/main/java/org/redisson/RedissonBatch.java
  redisson/src/main/java/org/redisson/RedissonSearch.java
  redisson/src/main/java/org/redisson/api/RBatch.java
  redisson/src/main/java/org/redisson/api/RBatchReactive.java
  redisson/src/main/java/org/redisson/api/RBatchRx.java
  redisson/src/main/java/org/redisson/reactive/RedissonBatchReactive.java
  redisson/src/main/java/org/redisson/rx/RedissonBatchRx.java
Labels: feature
